SUPPORTED_NDPI = set([
    "ftp", "pop", "smtp", "imap", 
    "dns", "ipp", "http", "mdns", 
    "ntp", "netbios", "nfs", "ssdp", 
    "bgp", "snmp", "xdmcp", "smb", 
    "syslog", "dhcp", "postgresql", "mysql", 
    "tds", "directdownloadlink", "i23v5", "applejuice", 
    "directconnect", "socrates", "vmware", "pando", 
    "filetopia", "imesh", "kontiki", "openft", 
    "kazaa/fasttrack", "gnutella", "edonkey", "bittorrent", 
    "off", "avi", "flash", "ogg", 
    "mpeg", "quicktime", "realmedia", "windowsmedia", 
    "mms", "xbox", "qq", "move", 
    "rtsp", "feidian", "icecast", "pplive", 
    "ppstream", "zattoo", "shoutcast", "sopcast", 
    "tvants", "tvuplayer", "veohtv", "qqlive", 
    "thunder/webthunder", "soulseek", "irc", "jabber", 
    "msn", "oscar", "yahoo", "battlefield", 
    "quake", "vrrp", "steam", "halflife2", 
    "world of warcraft", "telnet", "stun", "ipsec", 
    "gre", "icmp", "igmp", "egp", 
    "sctp", "ospf", "ip in ip", "rtp", 
    "rdp", "vnc", "pcanywhere", "ssl", 
    "ssh", "usenet", "mgcp", "iax", 
    "tftp", "afp", "stealthnet", "aimini", 
    "sip", "truphone", "icmpv6", "dhcpv6", 
    "armagetron", "crossfire", "dofus", "fiesta", 
    "florensia", "guildwars", "http application activesync", "kerberos", 
    "ldap", "maplestory", "mssql", "pptp", 
    "warcraft3", "world of kung fu", "meebo", "facebook", 
    "twitter", "dropbox", "gmail", "google maps", 
    "youtube", "skype", "google", "dce rpc", 
    "netflow_ipfix", "sflow", "http connect (ssl over http)", "http proxy", 
    "netflix", "citrix", "citrixonline/gotomeeting", "apple (imessage, facetime‚Ä¶)", 
    "webex", "whatsapp", "apple icloud", "viber", 
    "apple itunes", "radius", "windowsupdate", "teamviewer", 
    "tuenti", "lotusnotes", "sap", "gtp", 
    "upnp", "llmnr", "remotescan", "spotify", 
    "h323", "openvpn", "noe", "ciscovpn", 
    "teamspeak", "tor", "ciscoskinny", "rtcp", 
    "rsync", "oracle", "corba", "ubuntuone", 
    "cnn", "wikipedia", "whois-das", "collectd", 
    "redis", "zeromq", "megaco", "quic", 
    "whatsapp voice", "stracraft", "teredo", "snapchat", 
    "simet", "opensignal", "99taxi", "globotv", 
    "deezer", "instagram", "microsoft cloud services", "twitch", 
    "kakaotalk voice and chat", "hotspotshield vpn", "1kxun", "hangout", 
    "mqtt", "rx", "coap", "git", 
    "diameter", "apache jserv protocol"])
NDPI_FLOWS_COMPLETE = set([f"ndpi_flows:num_flows__{x}" for x in SUPPORTED_NDPI])
NDPI_BYTES_RCVD_COMPLETE = set([f"ndpi:bytes_rcvd__{x}" for x in SUPPORTED_NDPI])
NDPI_BYTES_SENT_COMPLETE = set([f"ndpi:bytes_sent__{x}" for x in SUPPORTED_NDPI])

SUPPORTED_L4 = set([
    "ip", "icmp", "igmp", "ggp",
    "ipencap", "st2", "tcp", "cbt",
    "egp", "igp", "bbn-rcc", "nvp",
    "pup", "argus", "emcon", "xnet",
    "chaos", "udp", "mux", "dcn",
    "hmp", "prm", "xns-idp", "trunk-1",
    "trunk-2", "leaf-1", "leaf-2", "rdp",
    "irtp", "iso-tp4", "netblt", "mfe-nsp",
    "merit-inp", "sep", "3pc", "idpr",
    "xtp", "ddp", "idpr-cmtp", "tp++",
    "il", "ipv6", "sdrp", "ipv6-route",
    "ipv6-frag", "idrp", "rsvp", "gre",
    "mhrp", "bna", "esp", "ah",
    "i-nlsp", "swipe", "narp", "mobile",
    "tlsp", "skip", "ipv6-icmp", "ipv6-nonxt",
    "ipv6-opts", "cftp", "sat-expak", "kryptolan",
    "rvd", "ippc", "sat-mon", "visa",
    "ipcv", "cpnx", "cphb", "wsn",
    "pvp", "br-sat-mon", "sun-nd", "wb-mon",
    "wb-expak", "iso-ip", "vmtp", "secure-vmtp",
    "vines", "ttp", "nsfnet-igp", "dgp",
    "tcf", "eigrp", "ospf", "sprite-rpc",
    "larp", "mtp", "ax.25", "ipip",
    "micp", "scc-sp", "etherip", "encap",
    "gmtp", "ifmp", "pnni", "pim",
    "aris", "scps", "qnx", "a/n",
    "ipcomp", "snp", "compaq-peer", "ipx-in-ip",
    "vrrp", "pgm", "l2tp", "ddx",
    "iatp", "st", "srp", "uti",
    "smp", "sm", "ptp", "isis",
    "fire", "crtp", "crdup", "sscopmce",
    "iplt", "sps", "pipe", "sctp",
    "fc", "divert"])
L4_BYTES_RCVD_COMPLETE = set([f"l4protos:bytes_rcvd__{x}" for x in SUPPORTED_L4])
L4_BYTES_SENT_COMPLETE = set([f"l4protos:bytes_sent__{x}" for x in SUPPORTED_L4])

# To prevent new feature coming with new versions of ntopng
FEATURE_SET = set([
    "active_flows:flows_as_client",
    "active_flows:flows_as_server",
    "contacts:num_as_client",
    "contacts:num_as_server",
    "dns_qry_rcvd_rsp_sent:queries_packets",
    "dns_qry_rcvd_rsp_sent:replies_error_packets",
    "dns_qry_rcvd_rsp_sent:replies_ok_packets",
    "dns_qry_sent_rsp_rcvd:queries_packets",
    "dns_qry_sent_rsp_rcvd:replies_error_packets",
    "dns_qry_sent_rsp_rcvd:replies_ok_packets",
    "echo_packets:packets_rcvd",
    "echo_packets:packets_sent",
    "echo_reply_packets:packets_rcvd",
    "echo_reply_packets:packets_sent",
    #"engaged_alerts:alerts",
    "host_unreachable_flows:flows_as_client",
    "host_unreachable_flows:flows_as_server",
    #"l4protos:bytes_rcvd__x", with x an l4 protocol
    "misbehaving_flows:flows_as_client",
    "misbehaving_flows:flows_as_server",
    #"ndpi:bytes_rcvd__x", with x a supported application
    #"ndpi:bytes_sent__x",
    #"ndpi_flows:num_flows__x",
    "tcp_packets:packets_rcvd",
    "tcp_packets:packets_sent",
    "tcp_rx_stats:lost_packets",
    "tcp_rx_stats:out_of_order_packets",
    "tcp_rx_stats:retransmission_packets",
    "tcp_tx_stats:lost_packets",
    "tcp_tx_stats:out_of_order_packets",
    "tcp_tx_stats:retransmission_packets",
    #"total_alerts:alerts",
    #"total_flow_alerts:alerts",
    "total_flows:flows_as_client",
    "total_flows:flows_as_server",
    "traffic:bytes_rcvd",
    "traffic:bytes_sent",
    "udp_pkts:packets_rcvd",
    "udp_pkts:packets_sent",
    "udp_sent_unicast:bytes_sent_non_unicast",
    "udp_sent_unicast:bytes_sent_unicast",
    "unreachable_flows:flows_as_client",
    "unreachable_flows:flows_as_server"])
