import numpy as np
import logging
import copy
from collections import defaultdict


# ----- ----- NDPI ----- ----- #
# ----- ----- ---- ----- ----- #
NDPI_DEFAULTS = { 
    "unknown":              "unspecified",
    "ftp_control":          "download-filetransfer-filesharing",
    "pop3":                 "email",
    "smtp":                 "email",
    "imap":                 "email",
    "dns":                  "network",
    "ipp":                  "system",
    "http":                 "web",
    "mdns":                 "network",
    "ntp":                  "system",
    "netbios":              "system",
    "nfs":                  "datatransfer",
    "ssdp":                 "system",
    "bgp":                  "network",
    "snmp":                 "network",
    "xdmcp":                "remoteaccess",
    "smbv1":                "system",
    "syslog":               "system",
    "dhcp":                 "network",
    "postgresql":           "database",
    "mysql":                "database",
    "hotmail":              "email",
    "direct_download_link": "download-filetransfer-filesharing",
    "pops":                 "email",
    "applejuice":           "download-filetransfer-filesharing",
    "directconnect":        "download-filetransfer-filesharing",
    "ntop":                 "network",
    "coap":                 "rpc",
    "vmware":               "remoteaccess",
    "smtps":                "email",
    "facebookzero":         "socialnetwork",
    "ubntac2":              "network",
    "kontiki":              "media",
    "openft":               "download-filetransfer-filesharing",
    "fasttrack":            "download-filetransfer-filesharing",
    "gnutella":             "download-filetransfer-filesharing",
    "edonkey":              "download-filetransfer-filesharing",
    "bittorrent":           "download-filetransfer-filesharing",
    "skypecall":            "voip",
    "signal":               "chat",
    "memcached":            "network",
    "smbv23":               "system",
    "mining":               "mining",
    "nestlogsink":          "cloud",
    "modbus":               "network",
    "whatsappcall":         "voip",
    "datasaver":            "web",
    "xbox":                 "game",
    "qq":                   "chat",
    "tiktok":               "socialnetwork",
    "rtsp":                 "media",
    "imaps":                "email",
    "icecast":              "media",
    "pplive":               "media",
    "ppstream":             "video",
    "zattoo":               "video",
    "shoutcast":            "music",
    "sopcast":              "video",
    "tvants":               "video",
    "tvuplayer":            "video",
    "http_download":        "download-filetransfer-filesharing",
    "qqlive":               "video",
    "thunder":              "download-filetransfer-filesharing",
    "soulseek":             "download-filetransfer-filesharing",
    "ps_vue":               "video",
    "irc":                  "chat",
    "ayiya":                "network",
    "unencrypted_jabber":   "web",
    "msn":                  "web",
    "oscar":                "chat",
    "yahoo":                "web",
    "battlefield":          "game",
    "googleplus":           "socialnetwork",
    "vrrp":                 "network",
    "steam":                "game",
    "halflife2":            "game",
    "worldofwarcraft":      "game",
    "telnet":               "remoteaccess",
    "stun":                 "network",
    "ipsec":                "vpn",
    "gre":                  "network",
    "icmp":                 "network",
    "igmp":                 "network",
    "egp":                  "network",
    "sctp":                 "network",
    "ospf":                 "network",
    "ip_in_ip":             "network",
    "rtp":                  "media",
    "rdp":                  "remoteaccess",
    "vnc":                  "remoteaccess",
    "pcanywhere":           "remoteaccess",
    "tls":                  "web",
    "ssh":                  "remoteaccess",
    "usenet":               "web",
    "mgcp":                 "voip",
    "iax":                  "voip",
    "tftp":                 "datatransfer",
    "afp":                  "datatransfer",
    "stealthnet":           "download-filetransfer-filesharing",
    "aimini":               "download-filetransfer-filesharing",
    "sip":                  "voip",
    "truphone":             "voip",
    "icmpv6":               "network",
    "dhcpv6":               "network",
    "armagetron":           "game",
    "crossfire":            "rpc",
    "dofus":                "game",
    "fiesta":               "game",
    "florensia":            "game",
    "guildwars":            "game",
    "http_activesync":      "cloud",
    "kerberos":             "network",
    "ldap":                 "system",
    "maplestory":           "game",
    "mssql-tds":            "database",
    "pptp":                 "vpn",
    "warcraft3":            "game",
    "worldofkungfu":        "game",
    "slack":                "collaborative",
    "facebook":             "socialnetwork",
    "twitter":              "socialnetwork",
    "dropbox":              "cloud",
    "gmail":                "email",
    "googlemaps":           "web",
    "youtube":              "media",
    "skype":                "voip",
    "google":               "web",
    "dce_rpc":              "rpc",
    "netflow":              "network",
    "sflow":                "network",
    "http_connect":         "web",
    "http_proxy":           "web",
    "citrix":               "network",
    "netflix":              "video",
    "lastfm":               "music",
    "waze":                 "web",
    "youtubeupload":        "media",
    "hulu":                 "streaming",
    "checkmk":              "datatransfer",
    "ajp":                  "web",
    "apple":                "web",
    "webex":                "voip",
    "whatsapp":             "chat",
    "appleicloud":          "web",
    "viber":                "voip",
    "appleitunes":          "streaming",
    "radius":               "network",
    "windowsupdate":        "softwareupdate",
    "teamviewer":           "remoteaccess",
    "tuenti":               "voip",
    "lotusnotes":           "collaborative",
    "sap":                  "network",
    "gtp":                  "network",
    "upnp":                 "network",
    "llmnr":                "network",
    "remotescan":           "network",
    "spotify":              "music",
    "messenger":            "voip",
    "h323":                 "voip",
    "openvpn":              "vpn",
    "noe":                  "voip",
    "ciscovpn":             "vpn",
    "teamspeak":            "voip",
    "tor":                  "vpn",
    "ciscoskinny":          "voip",
    "rtcp":                 "voip",
    "rsync":                "datatransfer",
    "oracle":               "database",
    "corba":                "rpc",
    "ubuntuone":            "cloud",
    "whois-das":            "network",
    "collectd":             "system",
    "socks":                "web",
    "nintendo":             "game",
    "rtmp":                 "media",
    "ftp_data":             "download-filetransfer-filesharing",
    "wikipedia":            "web",
    "zeromq":               "rpc",
    "amazon":               "web",
    "ebay":                 "shopping",
    "cnn":                  "web",
    "megaco":               "voip",
    "redis":                "database",
    "pando_media_booster":  "web",
    "vhua":                 "voip",
    "telegram":             "chat",
    "vevo":                 "music",
    "pandora":              "streaming",
    "quic":                 "web",
    "zoom":                 "video",
    "eaq":                  "network",
    "ookla":                "network",
    "amqp":                 "rpc",
    "kakaotalk":            "chat",
    "kakaotalk_voice":      "voip",
    "twitch":               "video",
    "doh_dot":              "network",
    "wechat":               "chat",
    "mpeg_ts":              "media",
    "snapchat":             "socialnetwork",
    "sina(weibo)":         "socialnetwork",
    "googlehangoutduo":     "voip",
    "iflix":                "video",
    "github":               "collaborative",
    "bjnp":                 "system",
    "free_205":             "voip",
    "wireguard":            "vpn",
    "smpp":                 "download-filetransfer-filesharing",
    "dnscrypt":             "network",
    "tinc":                 "vpn",
    "deezer":               "music",
    "instagram":            "socialnetwork",
    "microsoft":            "cloud",
    "starcraft":            "game",
    "teredo":               "network",
    "hotspotshield":        "vpn",
    "imo":                  "voip",
    "googledrive":          "cloud",
    "ocs":                  "media",
    "office365":            "collaborative",
    "cloudflare":           "web",
    "ms_onedrive":          "cloud",
    "mqtt":                 "rpc",
    "rx":                   "rpc",
    "applestore":           "softwareupdate",
    "opendns":              "web",
    "git":                  "collaborative",
    "drda":                 "database",
    "playstore":            "softwareupdate",
    "someip":               "rpc",
    "fix":                  "rpc",
    "playstation":          "game",
    "pastebin":             "download-filetransfer-filesharing",
    "linkedin":             "socialnetwork",
    "soundcloud":           "music",
    "csgo":                 "game",
    "lisp":                 "cloud",
    "diameter":             "network",
    "applepush":            "cloud",
    "googleservices":       "web",
    "amazonvideo":          "cloud",
    "googledocs":           "collaborative",
    "whatsappfiles":        "download-filetransfer-filesharing",
    "targus dataspeed":      "network",
    "dnp3":                 "network",
    "iec60870":             "network",
    "bloomberg":            "network",
    "capwap":               "network",
    "zabbix":               "network",
    "s7comm":               "network"
}


class key_dependent_dict(defaultdict):
    """https://www.reddit.com/r/Python/comments/27crqg/making_defaultdict_create_defaults_that_are_a/
    """
    def __init__(self, f_of_x, basedict):
        super().__init__(None, basedict) # base class doesn't get a factory
        self.f_of_x = f_of_x # save f(x)

    def __missing__(self, key): # called when a default needed
        ret = self.f_of_x(key) # calculate default value
        self[key] = ret # and install it in the dict
        return ret


def ndpi_value2cat(x):
    logging.warning(f"unknown L7 protocol {x}")
    return "unmapped ndpi"


NDPI_VALUE2CAT = key_dependent_dict(ndpi_value2cat, NDPI_DEFAULTS)
NDPI_FLOWS_COMPLETE = set({f"ndpi_flows:num_flows__{x}" for x in NDPI_VALUE2CAT.values()})
NDPI_BYTES_RCVD_COMPLETE = set({f"ndpi:bytes_rcvd__{x}" for x in NDPI_VALUE2CAT.values()})
NDPI_BYTES_SENT_COMPLETE = set({f"ndpi:bytes_sent__{x}" for x in NDPI_VALUE2CAT.values()})
NDPI_COMPLETE = NDPI_FLOWS_COMPLETE | NDPI_BYTES_RCVD_COMPLETE | NDPI_BYTES_SENT_COMPLETE


# ----- ----- FEATURES ----- ----- #
# ----- ----- -------- ----- ----- #
BASIC_LEVEL_LOW = set({
    "traffic:bytes_rcvd", "traffic:bytes_sent", 
    "echo_packets:packets_rcvd", "echo_packets:packets_sent",
    "echo_reply_packets:packets_rcvd", "echo_reply_packets:packets_sent",
    "tcp_packets:packets_rcvd", "tcp_packets:packets_sent",
    "tcp_rx_stats:lost_packets", "tcp_rx_stats:out_of_order_packets",
    "tcp_rx_stats:retransmission_packets", "tcp_tx_stats:lost_packets",
    "tcp_tx_stats:out_of_order_packets", "tcp_tx_stats:retransmission_packets",
    "udp_pkts:packets_rcvd", "udp_pkts:packets_sent",
    "udp_sent_unicast:bytes_sent_non_unicast", "udp_sent_unicast:bytes_sent_unicast"})

BASIC_LEVEL_HIGH = set({
    "active_flows:flows_as_client", "active_flows:flows_as_server",
    "total_flows:flows_as_client", "total_flows:flows_as_server",
    "misbehaving_flows:flows_as_client", "misbehaving_flows:flows_as_server",
    "unreachable_flows:flows_as_client", "unreachable_flows:flows_as_server",
    "host_unreachable_flows:flows_as_client", "host_unreachable_flows:flows_as_server",
    "dns_qry_rcvd_rsp_sent:queries_packets",
    "dns_qry_rcvd_rsp_sent:replies_error_packets",
    "dns_qry_rcvd_rsp_sent:replies_ok_packets",
    "dns_qry_sent_rsp_rcvd:queries_packets",
    "dns_qry_sent_rsp_rcvd:replies_error_packets",
    "dns_qry_sent_rsp_rcvd:replies_ok_packets",
    "contacts:num_as_client", "contacts:num_as_server",
})
# To prevent new feature coming with new versions of ntopng
BASIC_FEATURES = BASIC_LEVEL_LOW | BASIC_LEVEL_HIGH
FEATURES_COMPLETE = copy.deepcopy(BASIC_FEATURES)
FEATURES_COMPLETE |= NDPI_FLOWS_COMPLETE | NDPI_BYTES_RCVD_COMPLETE | NDPI_BYTES_SENT_COMPLETE


# ----- ----- FEATURES LEVELS ----- ----- #
# ----- ----- --------------- ----- ----- #
FEATURE_LEVELS = {
    "high": NDPI_COMPLETE | BASIC_LEVEL_HIGH,
    "smart": NDPI_FLOWS_COMPLETE | set({
        "active_flows:flows_as_server", "active_flows:flows_as_client",
        "traffic:bytes_rcvd", "traffic:bytes_sent", 
        "contacts:num_as_client", "contacts:num_as_server",
        "dns_qry_sent_rsp_rcvd:replies_error_packets",
        "dns_qry_sent_rsp_rcvd:replies_ok_packets",
        }),
    "low": BASIC_LEVEL_LOW
}

